from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

MARKER = "<!-- generated by pm-multimodels; do not edit -->"

CODEX_MAPPING = """## Claude Code Compatibility

Translate Claude-specific instructions by capability:

- `Read` -> read files with the available file or shell tools.
- `Edit` and `Write` -> use the available patch/edit tool.
- `Glob` and `Grep` -> use `rg --files` and `rg`.
- `Bash` -> use the primary shell execution tool.
- `Skill` -> load and follow the referenced `SKILL.md`.
- `AskUserQuestion` -> use structured user input when available; otherwise ask in chat and wait.
- `WebFetch` and `WebSearch` -> use the relevant web or documentation tool.
- `Task` and Claude subagents -> use available subagent tools only when supported; otherwise work inline.
- Claude slash commands -> use the corresponding Codex skill or custom prompt.
- Unsupported lifecycle tools -> stop and explain the missing capability instead of pretending success.
"""

CURSOR_MAPPING = """## Claude Code Compatibility

Translate Claude-specific instructions by capability:

- `Read`, `Edit`, `Write`, `Glob`, and `Grep` -> use Cursor's equivalent file tools.
- `Bash` -> use Cursor's shell tool.
- `Skill` -> load and follow the referenced `SKILL.md`.
- `AskUserQuestion` -> ask conversationally and wait for the answer.
- `WebFetch` and `WebSearch` -> use Cursor's web tools when available.
- `Task` and Claude subagents -> use Cursor subagents when available; otherwise work inline.
- Claude slash commands -> use the corresponding Cursor command or skill.
- Unsupported lifecycle tools -> stop and explain the missing capability instead of pretending success.
"""


def digest(data: str | bytes) -> str:
    if isinstance(data, str):
        data = data.encode()
    return hashlib.sha256(data).hexdigest()


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, text
    raw = text[4:end]
    body = text[end + 5 :]
    fields: dict[str, str] = {}
    for key in ("name", "description", "argument-hint"):
        match = re.search(rf"(?m)^{key}:\s*(.+)$", raw)
        if match:
            fields[key] = match.group(1).strip().strip("\"'")
    return fields, body


def normalize_name(value: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return value[:64] or "unnamed"


def adapt_body(body: str, platform: str) -> str:
    home = "$HOME/.codex" if platform == "codex" else "$HOME/.cursor"
    body = body.replace("$HOME/.claude", home)
    body = body.replace("~/.claude", home)
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", "${PLUGIN_ROOT}")
    if platform == "codex":
        body = re.sub(r"(?<![\w.$@~-])/([a-zA-Z0-9][\w:-]*)", r"$\1", body)
        body = body.replace("$ARGUMENTS", "{{ARGS}}")
    else:
        body = body.replace("$ARGUMENTS", "{{ARGS}}")
    return body


def adapt_skill(source: Path, platform: str) -> tuple[str, str]:
    text = source.read_text()
    fields, body = split_frontmatter(text)
    name = normalize_name(fields.get("name") or source.parent.name)
    description = fields.get("description") or f"Adapted Claude skill: {name}"
    mapping = CODEX_MAPPING if platform == "codex" else CURSOR_MAPPING
    output = (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "---\n\n"
        f"{MARKER}\n\n"
        f"{mapping}\n"
        f"{adapt_body(body, platform).lstrip()}"
    )
    return name, output


def adapt_command(
    source: Path, platform: str, command_name: str | None = None
) -> tuple[str, str]:
    text = source.read_text()
    fields, body = split_frontmatter(text)
    base_name = normalize_name(command_name or source.stem)
    description = fields.get("description") or f"Run the adapted Claude command {base_name}"
    mapping = CODEX_MAPPING if platform == "codex" else CURSOR_MAPPING

    if platform == "codex":
        name = normalize_name(f"claude-command-{base_name}")
        output = (
            "---\n"
            f"name: {name}\n"
            f"description: {description}. Use when the user invokes or requests the Claude command `{base_name}`.\n"
            "---\n\n"
            f"{MARKER}\n\n"
            f"{mapping}\n"
            "Treat all user text following the command name as `{{ARGS}}`.\n\n"
            f"{adapt_body(body, platform).lstrip()}"
        )
    else:
        name = base_name
        adapted = adapt_body(body, platform).replace("{{ARGS}}", "$ARGUMENTS")
        output = (
            "---\n"
            f"description: {description}\n"
            "---\n\n"
            f"{MARKER}\n\n"
            f"{mapping}\n"
            f"{adapted.lstrip()}"
        )
    return name, output


def adapt_codex_prompt(source: Path) -> str:
    text = source.read_text()
    fields, body = split_frontmatter(text)
    description = fields.get("description") or f"Adapted Claude command {source.stem}"
    hint = fields.get("argument-hint")
    frontmatter = ["---", f"description: {json.dumps(description)}"]
    if hint:
        frontmatter.append(f"argument-hint: {json.dumps(hint)}")
    frontmatter.append("---")
    adapted = adapt_body(body, "codex").replace("{{ARGS}}", "$ARGUMENTS")
    return "\n".join(frontmatter) + f"\n\n{MARKER}\n\n{CODEX_MAPPING}\n{adapted.lstrip()}"


def self_update_block(update_command: str) -> str:
    return f"""## pm-multimodels Self-Update

Before doing pm-multimodels work, run `{update_command} update-check`.
If it prints `UPGRADE_AVAILABLE <old> <new>`, tell the user a pm-multimodels update is available and offer to run `{update_command} upgrade` to install it (this also re-syncs Codex and Cursor).
"""


def codex_agents_adapter(claude_path: Path, update_command: str | None = None) -> str:
    source_hash = digest(claude_path.read_bytes())
    block = f"\n{self_update_block(update_command)}" if update_command else ""
    return f"""# AGENTS.md

{MARKER}
<!-- canonical-source: CLAUDE.md sha256:{source_hash} -->

## Canonical Project Instructions

Before doing project work, read `CLAUDE.md` in full. It is the canonical source for project architecture, commands, conventions, testing, and workflow.

{CODEX_MAPPING}

When `CLAUDE.md` conflicts with this compatibility section, preserve the project intent and translate only the tool invocation. Do not edit `CLAUDE.md` as part of synchronization.
{block}"""


def cursor_rule_adapter(claude_path: Path, update_command: str | None = None) -> str:
    source_hash = digest(claude_path.read_bytes())
    block = f"\n{self_update_block(update_command)}" if update_command else ""
    return f"""---
description: Translate canonical CLAUDE.md tooling for Cursor Agent and Cursor CLI
alwaysApply: true
---

{MARKER}
<!-- canonical-source: CLAUDE.md sha256:{source_hash} -->

`CLAUDE.md` is the canonical project instruction source.

{CURSOR_MAPPING}
{block}"""
